### ISSUE TITLE
Example of minimal HEC kubernetes deployment?

### ISSUE THREAD

**Issue by aegershman** [splunk/docker-splunk#138]
Are there examples of a simple Splunk HEC deployed on kubernetes? [The examples in the `test_results` folder](https://github.com/splunk/docker-splunk/tree/develop/test_scenarios/kubernetes) are for full-fledged deployments with multiple components. 

## background

My use-case is running a [splunk-firehose-nozzle on Cloud Foundry](https://github.com/cloudfoundry-community/splunk-firehose-nozzle). The firehose nozzle forwards application logs to the HEC (running on kubernetes), and then the HEC performs transform rules to route the logs to their proper index, and is then forwarded to the appropriate indexer. It's entirely stateless.

I don't own the indexer. I'm just trying to help get people's logs from Cloud Foundry to our enterprise Splunk.

Just wondering if anyone has done anything similar + has an example of how they did it?

**Comment by nwang92** [comment]
I'm not too familiar with the specifics of that Cloud Foundry project, but just glancing over the README I'd suggest the following:
1. Bundle up the configs outlined [here](https://github.com/cloudfoundry-community/splunk-firehose-nozzle#index-routing) into some lightweight app in the format of:
```
splunk_app_cf/
    default/
        app.conf
        props.conf
        transforms.conf
```
You can probably modify the props.conf + transforms.conf here and cater them to your team's specific needs. 

2. Use the `splunk/splunk` image as a set of heavy forwarders, following some of the topologies outlined [here](https://docs.splunk.com/Documentation/Forwarder/7.2.4/Forwarder/Forwarderdeploymenttopologies)
If you have access to the hostnames/IPs of your indexers from your k8s cluster, you could create a deployment that will act as a forwarder pool. Something like the following might get you going:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splunk-heavy-forwarder 
  labels:
    app: splunk
    role: splunk-heavy-forwarder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: splunk
        role: splunk-heavy-forwarder
    spec:
      hostname: forwarder
      containers:
        - name: forwarder
          image: splunk/splunk:latest
          env:
            - name: SPLUNK_ROLE
              value: splunk_heavy_forwarder
            - name: SPLUNK_PASSWORD
              value: helloworld
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_INDEXER_URL
              value: 10.111.111.111,10.222.222.222,indexer.company.com 
            - name: SPLUNK_APPS_URL
              value: http://fileserver/path/to/splunk_app_cf.tgz
            - name: SPLUNK_HEC_TOKEN
              value: abcd1234
          ports:
            - name: hec
              containerPort: 8088
```

After this, you can follow up by creating a service type to your liking over the 8088 HEC port. This should allow you to send data through HEC through your forwarder pool in k8s that eventually lands in your on-prem indexers.

Let me know if that all makes sense, or if I missed some points you wanted to address!

**Comment by aegershman** [comment]
Awesome, thanks for your response. 

I currently have the routing rules setup as a k8s `configmap`, but I hadn't considered packaging the configuration up as an app & consuming it on the HEC as a `.tgz`. I'll explore that idea more.

Could I also [specify the config for `splunk_app_cf` as custom config](https://github.com/splunk/docker-splunk/blob/0684bff877d10dab0de52316514d41205ecd939d/docs/ADVANCED.md#create-custom-configs) instead of taring up as an app?

E.g.,:

```
splunk_app_cf/
    default/
        app.conf
        props.conf
        transforms.conf
````

would instead be specified in `defaults.yml` as...

```
splunk:
  conf:
    app.conf:
      directory: /opt/splunk/etc/apps/splunk_app_cf
      content:
        blah: blahblah
        foo: foofofoffo
    transforms.conf:
      directory: /opt/splunk/etc/apps/splunk_app_cf
      content:
        abc: 123
    props.conf:
      directory: /opt/splunk/etc/apps/splunk_app_cf
      content:
           xyz: blahblahblah
```

... or do you think that's poor design?
