### ISSUE TITLE
Running the universal forwarder as a sidercar on kubernetes

### ISSUE THREAD

**Issue by sayeedc** [splunk/docker-splunk#186]
Is there any information on how to run the UF as sidecar container to read logs from a file?

**Comment by nwang92** [comment]
I guess we don't have many docs around this - I can add that. There's a few articles out there that already do this, but you could start off with an example like:
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: splunk-uf
    image: splunk/universalforwarder:latest
    imagePullPolicy: Always
    env:
    - name: SPLUNK_START_ARGS
      value: --accept-license
    - name: SPLUNK_PASSWORD
      value: helloworld
    - name: SPLUNK_CMD
      value: add monitor /var/log/
    volumeMounts:
    - name: shared-data
      mountPath: /var/log
  - name: my-app
    image: my-app
    volumeMounts:
    - name: shared-data
      mountPath: /app/logs/
  volumes:
  - name: shared-data
    emptyDir: {}
```

Obviously, that's the most basic example - you'd probably also want another envvar on your `uf` container to send its internal + application logs somewhere more permanent. But you can take this pod template and put it in a higher-order controller like a Deployment or DaemonSet.
