### ISSUE TITLE
How to specify the UID/GID inside the container that Splunk uses?

### ISSUE THREAD

**Issue by neogeek83** [splunk/docker-splunk#265]
So I need to have my Splunk data stored outside the container(for easier data ingest,backup, and config updates), and used via a volume. Okay, no worries, that's working fine. The next issue is I need to change the ownership of the files, so need to change the UID/GID of the `splunk` user inside the container to `uid=404 gid=404`. Why? The default `splunk` user with `uid=999 guid=999` conflicts with another user on my host system which I don't want to have access to the Splunk data, and it can not be changed... 

How can I specify the UID/GID inside the container that Splunk uses?

my `docker-compose.yml` looks like this:
```
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    hostname: splunk
    ports:
      - "${SPLUNK_PORT}:8000"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
    volumes:
      - ./splunk/logs/:/var/log/input_logs
      - ./splunk/etc/:/opt/splunk/etc/
      - ./splunk/var/:/opt/splunk/var/
      - ./splunk/data/:/opt/splunk/var/lib/splunk
```

This appears to not be supported currently, so is a bug / feature request. If it is supported, it's a documentation update request.

**Comment by neogeek83** [comment]
I presume using volumes like this is the preferred/suggested way we're supposed to be making updates to the configs  dashboards and such... If I'm missing something and doing it wrong, that'd be good to know as well. Thanks!

**Comment by bb03** [comment]
We'll start investigating what integrating this into our environment variables would look like.  In the meantime, you might want to check out the ansible_pre_tasks variable https://github.com/splunk/splunk-ansible/blob/develop/site.yml#L21.  This should allow you to run custom ansible plays before executing our main role configuration.

**Comment by bb03** [comment]
The environment variable that the above maps to is SPLUNK_ANSIBLE_PRE_TASKS

**Comment by defektive** [comment]
@neogeek83 I just did this. I am not sure where you are getting UID/GID of 999 for the splunk user. [The default is 41812](https://github.com/splunk/docker-splunk/blob/dc7d3211e4b55810b2f6a92557e77ac06403b145/splunk/common-files/Dockerfile#L50). Maybe you're on a different/older image.

Since the default IDs are specified as arguments you could build your own image with different args.
```
docker build --build-arg UID=404 --build-arg GID=404
```

I ended up creating a new user and group with the IDs of 41812, since it was easier than building my own image.

Hope this helps.

**Comment by romanmelko** [comment]
Interesting. My current approach is the following to make it happen:

In outside Ansible playbook (not inside the container, my own one which is used to prepare the environment, define volumes etc.) I determine dynamically the user who executed the playbook with:
```
- name: "Determine user UID"
  shell: "id {{ ansible_env.USER }} | awk '{print $1}' | cut -d= -f2 | cut -d'(' -f1"
  register: user_uid
- name: "Define user UID variable"
  set_fact: 
    splunk_service_uid: "{{ user_uid.stdout }}"
```
Then I pass the UID to Dockerfile via Ansible template:
```
ENV SPLUNK_HOME=/opt/splunk
ENV SPLUNK_SERVICE_USER=splunk
ENV SPLUNK_SERVICE_UID={{ splunk_service_uid }}
RUN sudo usermod -u $SPLUNK_SERVICE_UID $SPLUNK_SERVICE_USER
RUN sudo chown -R $SPLUNK_SERVICE_USER $SPLUNK_HOME 
```
which just changes the UID and ownership inside the container. But looks like approach by @defektive of doing so might be better.
