### ISSUE TITLE
Splunk Enterprise hangs on start on Kubernetes 1.15.4

### ISSUE THREAD

**Issue by cmanzi** [splunk/docker-splunk#294]
I am currently trying to run Splunk Enterprise on Kubernetes 1.15.4. I was able to run this image previously, but I believe that was when we were on Kubernetes 1.14.x. After encountering some issues with the latest image (8.0), seemingly related to https://github.com/splunk/docker-splunk/issues/272, I decided to try the 'legacy' image without Ansible instead. 

Here is what I am seeing: I can run the docker image locally with no issues. However, when I try to run any `bin/splunk` command inside of the container in Kubernetes 1.15.4, it inevitably locks up. This is the last entry I see in the logs: 
```
Moving '/opt/splunk-app/share/splunk/search_mrsparkle/modules.new' to '/opt/splunk-app/share/splunk/search_mrsparkle/modules'.
```
ps -ef shows the process running at max CPU allocated to the container (same behavior as with the 8.0 Ansible image):
```
splunk@splunk-0:/opt/splunk-app$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
splunk       1     0  0 16:57 ?        00:00:00 /bin/bash /opt/splunk-app/entrypoint.sh
splunk      14     1 42 16:57 ?        00:12:07 /opt/splunk-app/bin/splunk start --debug --answer-no --accept-license
splunk      27     0  0 17:05 pts/0    00:00:00 bash
splunk      69    27  0 17:25 pts/0    00:00:00 ps -ef
```
After running strace -f on the entrypoint script, I see that the `splunk` process locks up at the last call shown here:
```
[pid  7557] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=0, si_uid=999, si_status=0, si_utime=0, si_stime=0} ---
[pid  7557] wait4(64, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 64
[pid  7557] munmap(0x7f1ddb758000, 4096) = 0
[pid  7557] lstat("/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  7557] lstat("/bin/sh", {st_mode=S_IFLNK|0777, st_size=4, ...}) = 0
[pid  7557] readlink("/bin/sh", "dash", 4095) = 4
[pid  7557] lstat("/bin/dash", {st_mode=S_IFREG|0755, st_size=125400, ...}) = 0
```

The container is running as the `splunk` user,  and the mounted volumes have the correct permissions/gid applies.

**Comment by nwang92** [comment]
Can you supply the manifest you're using to bring up the `splunk-0` pod? Also any other info on `LimitRange` or potentially other resource quotas in the namespace you're deploying into would be helpful and good to know.

**Comment by nwang92** [comment]
Also what Kubernetes platform are you using? GKE/EKS/minikube/straight kubeadm? :P Not sure if that matters at all, but if I can I'd like to replicate your exact environment.

**Comment by cmanzi** [comment]
@nwang92 Thanks for your replies. I'm deploying using a slightly customized version of Kops. I'm deploying as a statefulset, here is the manifest:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    apps: splunk
  name: splunk
  namespace: logging
spec:
  replicas: 1
  serviceName: splunk
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      serviceAccountName: splunk
      securityContext:
        fsGroup: 999
      containers:
      - env:
        - name: SPLUNK_PASSWORD
          value: <password>
        - name: SPLUNK_HEC_TOKEN
          value: <token>
        - name: SPLUNK_START_ARGS
          value: --accept-license
        - name: SPLUNK_USER
          value: root
        - name: SPLUNK_HOME
          value: /opt/splunk-app
        image: splunk/splunk:7.0.3
        name: splunk
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8088
          name: https-hec
        livenessProbe:
          tcpSocket:
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /services/collector/health
            port: https-hec
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
        volumeMounts:
        - name: splunk-data
          mountPath: "/opt/splunk-app/var"
        - name: splunk-etc
          mountPath: "/opt/splunk-app/etc"
      volumes:
      - name: host-ca
        hostPath:
          path: /etc/ssl/certs
  volumeClaimTemplates:
  - metadata:
      name: splunk-etc
      annotations: {}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "1Gi"
      storageClassName: gp2-encrypted-retain
  - metadata:
      name: splunk-data
      annotations: {}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "5Gi"
      storageClassName: gp2-encrypted-retain
```
