### ISSUE TITLE
container Always expect a password flag to be passed

### ISSUE THREAD

**Issue by getkub** [splunk/docker-splunk#318]
The Splunk docker image expects the password to be passed in command line.  This prevents full blown automation (using k8s or compose).  

In older versions of this image, the bootstrapping could have been done using
```
SPLUNK_BEFORE_START_CMD=edit user admin -password {{newPass}} -role admin -auth admin:changeme
```
OR using
`user-seed.conf`

But these are NOT possible as the current version expects password is always passed !!
Error shown below from `docker logs` 

```
TASK [splunk_common : Hash the password] ***************************************
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": [
        "/opt/splunk/bin/splunk", 
        "hash-passwd"
    ], 
    "delta": "0:00:00.065287", 
    "end": "2020-02-14 11:48:35.577711", 
    "rc": 1, 
    "start": "2020-02-14 11:48:35.512424"
}

STDERR:

ERROR: Received 0 arguments, expected 1.
usage: hash-passwd PASSWORD
options:
-                   Dash '-' Indicates password is being passed via stdin.
examples:
splunkd hash-passwd SomePassW0rD 
cat passwd.txt | splunkd hash-passwd -

```

**Comment by nwang92** [comment]
> In older versions of this image, the bootstrapping could have been done using
`SPLUNK_BEFORE_START_CMD=edit user admin -password {{newPass}} -role admin -auth admin:changeme`

There was a change in Splunk version 7.0 (or 7.1?) which removed the default admin password of `changeme`. If you install any recent version of Splunk from scratch, splunkd will not start properly until you provide the [admin credentials](https://docs.splunk.com/Documentation/Splunk/latest/Security/Secureyouradminaccount).

So the previous `SPLUNK_BEFORE_START_CMD` command you used will no longer work, because `admin:changeme` is no longer a valid set of credentials. You can pass in a password using the `SPLUNK_PASSWORD` env var as such:
```
docker run -d -P -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld splunk/splunk:latest
```
and login to SplunkWeb using `admin:helloworld`.

**Comment by getkub** [comment]
> ```
> docker run -d -P -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld splunk/splunk:latest
> ```


I agree you can pass SPLUNK_PASSWORD flag on docker run, but that's very basic running on CLI

In real life purposes, like via docker-compose etc, such flags are not a possibility. It has to be part of a SPLUNK_BEFORE_START or some kind of at start time trigger which can be coded into a file needs to be present. 
And moreover we never use CLI passwords, but rather than hashed passwords even for demo. So that flexibility is also lost using the splunk docker images.

**Comment by nwang92** [comment]
`SPLUNK_PASSWORD` is an environment variable passed into the container at run-time. So the above CLI can be translated directly into a docker-compose.yml that looks like the following:
```yaml
version: "3.6"

services:
  so1:
    image: splunk/splunk:latest
    hostname: so1
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=helloworld
    ports:
      - 8000
```

As I understand it, the previous usage of `SPLUNK_BEFORE_START_CMD` was also an environment variable as well but correct me if I'm mistaken.

**Comment by nwang92** [comment]
> And moreover we never use CLI passwords, but rather than hashed passwords even for demo. So that flexibility is also lost using the splunk docker images.

As far as the security aspect goes, we would not recommend putting the admin password in plaintext - but that will inevitably be the case if you formerly used `SPLUNK_BEFORE_START_CMD` using the older format of the container image.

The latest Splunk Docker image supports setting parameters using a yaml file we refer to as the `default.yml`. This can be generated and used with something like:
```
$ docker run -e SPLUNK_PASSWORD=helloworld splunk/splunk:latest create-defaults > default.yml
$ docker run -d -P -e SPLUNK_START_ARGS=--accept-license -v ./default.yml:/tmp/defaults/default.yml splunk/splunk:latest
```
From there, you can dump that `default.yml` into your secrets engine, whether it be kube secrets, docker secrets, vault, etc.

Alternatively, if you're using K8S you can also do some fun stuff like:
```
apiVersion: v1
kind: Pod
metadata:
  name: splunk
spec:
  containers:
  - name: splunk
    image: splunk
    env:
      - name: SPLUNK_PASSWORD
        valueFrom:
          secretKeyRef:
            name: splunk-secrets
            key: password
...
```
