### ISSUE TITLE
Since Upgrade Splunk from 7.3.3 to 8.0.4.1 in Docker Ansible error

### ISSUE THREAD

**Issue by smonyan** [splunk/docker-splunk#385]
Hello everybody

I have the problem that since I'm update my docker containers with splunk from 7.3.3 to 8.0.4.1, I receive following error message:

TASK [Check all instances for required restarts] *******************************
fatal: [localhost]: FAILED! => {}
MSG:
The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'splunk' is undefined

The configuration is the same like on version 7.3.3. When I downgrade everything works fine again. Yes I'm use the default.yml to configure some .conf files in splunk and I'm use some basic variables in the deployment yaml. I think it has something to do with the default.yml, because other pods with a different configuration work with the same version. But I don't find the mistake. I hope you can help me. What has changed since version 7.x? is the default.yml read differently?

I have no mounts or volumes in the container, except the default.yml as configMap under /var/tmp/defaults/default.yml:

```yaml
        - name: SPLUNK_DEFAULTS_URL
          value: "/var/tmp/defaults/default.yml"
```
[deafult.txt](https://github.com/splunk/docker-splunk/files/4798905/deafult.txt)

**Comment by smonyan** [comment]
I correct myself, the problem exists since 7.3.5

**Comment by nwang92** [comment]
I don't believe that should have changed, we do have a test case for upgrading from [7.3.4](https://github.com/splunk/docker-splunk/blob/develop/tests/test_docker_splunk.py#L46) to the [latest](https://github.com/splunk/docker-splunk/blob/develop/tests/test_docker_splunk.py#L2380). I can test it with 7.3.5 and get back to you though.

**Comment by nwang92** [comment]
I'm not able to reproduce this, it seems like my upgrade is successful. But I did encounter a similar error when passing in bad parameters to the mount configuration (note, this is not Kubernetes):

This caused a problem because the directory was mounted within the container as a directory and it expected a file.
```
$ docker run -d -P -v "$(pwd):/var/tmp/defaults/default.yml" -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -e SPLUNK_DEFAULTS_URL=/var/tmp/defaults/default.yml splunk/splunk:7.3.5
...
[WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with script
plugin: Inventory script (/opt/ansible/inventory/environ.py) had an execution
error: Traceback (most recent call last):   File
"/opt/ansible/inventory/environ.py", line 688, in <module>     main()   File
"/opt/ansible/inventory/environ.py", line 674, in main
getSplunkInventory(inventory)   File "/opt/ansible/inventory/environ.py", line
90, in getSplunkInventory     inventory["all"]["vars"] = getDefaultVars()
File "/opt/ansible/inventory/environ.py", line 105, in getDefaultVars
defaultVars = loadDefaults()   File "/opt/ansible/inventory/environ.py", line
549, in loadDefaults     base = mergeDefaults(base, yml["key"], yml["src"])
File "/opt/ansible/inventory/environ.py", line 488, in mergeDefaults
vars_scope = mergeDefaultsFromFile(vars_scope, src)   File
"/opt/ansible/inventory/environ.py", line 525, in mergeDefaultsFromFile
with open(file, "r") as f: IOError: [Errno 21] Is a directory:
'/var/tmp/defaults/default.yml'
[WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with ini
plugin: /opt/ansible/inventory/environ.py:16: Expected key=value host variable
assignment, got: __future__
[WARNING]: Unable to parse /opt/ansible/inventory/environ.py as an inventory
source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [Run default Splunk provisioning] *****************************************
Tuesday 23 June 2020  16:42:29 +0000 (0:00:00.048)       0:00:00.048 **********

TASK [Gathering Facts] *********************************************************
ok: [localhost]
Tuesday 23 June 2020  16:42:32 +0000 (0:00:02.910)       0:00:02.959 **********
Tuesday 23 June 2020  16:42:32 +0000 (0:00:00.058)       0:00:03.018 **********
Tuesday 23 June 2020  16:42:32 +0000 (0:00:00.061)       0:00:03.080 **********
Tuesday 23 June 2020  16:42:32 +0000 (0:00:00.060)       0:00:03.141 **********

TASK [Check all instances for required restarts] *******************************
fatal: [localhost]: FAILED! => {}

MSG:

The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'splunk' is undefined

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

Tuesday 23 June 2020  16:42:32 +0000 (0:00:00.029)       0:00:03.171 **********
===============================================================================
Gathering Facts --------------------------------------------------------- 2.91s
Provision role ---------------------------------------------------------- 0.06s
Execute post-setup playbooks -------------------------------------------- 0.06s
Execute pre-setup playbooks --------------------------------------------- 0.06s
Check all instances for required restarts ------------------------------- 0.03s
ERROR: Couldn't read "/opt/splunk/etc/splunk-launch.conf" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?
```

This was corrected with a change in the `--volume` configuration on the container:
```
$ docker run -d -P -v "$(pwd):/var/tmp/defaults" -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -e SPLUNK_DEFAULTS_URL=/var/tmp/defaults/default.yml splunk/splunk:7.3.5
```

Not sure if that's of any assistance, but my guess is it's possible for the configmap mounting to be the issue?

**Comment by smonyan** [comment]
Sorry for my late response. The mount cannot be the problem, because we use kubernetes and the defaults.yml file will be mounted from a secret in the path /var/tmp/defaults/...

And no, the file isnt mounted as a directory with the name defaults.yml, thats the first thing that i checked. Thats the mount in the container:

splunk@splunk-hec-857c8c9c6c-8cc9g:/opt/splunk$ ls -al /var/tmp/defaults/default.yml
-rw-r--r-- 1 root splunk 1552 Jun 19 11:22 /var/tmp/defaults/default.yml

And like I said, with this configuration in my deployment, i have containers with version 8.x which work. the only thing that is different is the default.yml and that I don't set the HEC token as an environment variable.

**Comment by nwang92** [comment]
Did you see other warnings in the startup logs? At least from what I had above, there was some error with the inventory script uses to parse the environment variables.

Additionally, could you share the deployment spec yaml you're using to create this instance?

**Comment by smonyan** [comment]
I see the following warnings:

[WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with script
plugin: Inventory script (/opt/ansible/inventory/environ.py) had an execution
error: Traceback (most recent call last):   File
"/opt/ansible/inventory/environ.py", line 692, in <module>     main()   File
"/opt/ansible/inventory/environ.py", line 678, in main
getSplunkInventory(inventory)   File "/opt/ansible/inventory/environ.py", line
90, in getSplunkInventory     inventory["all"]["vars"] = getDefaultVars()
File "/opt/ansible/inventory/environ.py", line 109, in getDefaultVars
getHEC(defaultVars)   File "/opt/ansible/inventory/environ.py", line 405, in
getHEC     vars_scope["splunk"]["hec"]["port"] =
int(os.environ.get("SPLUNK_HEC_PORT", vars_scope["splunk"]["hec"].get("port")))
ValueError: invalid literal for int() with base 10: 'tcp://10.127.56.237:8088'
[WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with ini
plugin: /opt/ansible/inventory/environ.py:16: Expected key=value host variable
assignment, got: __future__
[WARNING]: Unable to parse /opt/ansible/inventory/environ.py as an inventory
source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

And that's my deplyoment.yaml for kubernetes:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-hec
  namespace: appl-splunk-ingest-t1
spec:
  selector:
    matchLabels:
      app: splunk-hec
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: splunk-hec
      annotations:
        collectord.io/output: "splunk"
        collectord.io/logs-index: "_internal"
    spec:
      securityContext:
        runAsUser: 41812
        fsGroup: 41812
      containers:
      - name: splunk-hec
        image: docker-remote.repo.pnet.ch/splunk/splunk:7.3.3
        imagePullPolicy: Always
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_ROLE
          value: "splunk_standalone"
        - name: SPLUNK_DEFAULTS_URL
          value: "/var/tmp/defaults/default.yml"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: v3t-splunk
              key: password
        - name: SPLUNK_HOME_OWNERSHIP_ENFORCEMENT
          value: "false"
        - name: SPLUNK_USER
          value: "splunk"
        - name: SPLUNK_GROUP
          value: "splunk"
        volumeMounts:
        - name: defaults
          mountPath: "/var/tmp"
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
              - /sbin/checkstate.sh
          initialDelaySeconds: 300
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/grep
              - started
              - /opt/container_artifact/splunk-container.state
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "6"
            memory: "6Gi"
      volumes:
      - name: defaults
        secret:
          secretName: v3t-splunk-hec
          items:
          - key: defaults
            path: defaults/default.yml
```
