### ISSUE TITLE
upgrade splunk version on running container

### ISSUE THREAD

**Issue by sarit12** [splunk/docker-splunk#391]
Hello
i had splunk version 7.2.6 and i wanted to upgrade to 8.0.2
the container already had splunk running and after upgrading im getting this error:

> > TASK [splunk_common : Check for existing splunk secret] ************************
> fatal: [localhost]: FAILED! => {
>     "changed": false
> }
> 
> MSG:
> 
> Permission denied
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0 

when running splunk version 8.0.2 on "clean" environment it is working fine.

how can i fix this error ?

thanks

**Comment by nwang92** [comment]
Are you using the image through Docker/Swarm or Kubernetes?

It seems like what's happening is when named volumes are mounted on the new container they appear to be owned by `ansible` instead of `splunk`. This might be a side-effect of the default `ansible` user on the container? But knowing which orchestrator you're using would help in providing the appropriate solution.

**Comment by sarit12** [comment]
Hello.
thanks for your answer
i'm using image through Docker but running with Kubernetese.

**Comment by nwang92** [comment]
Perfect, in that case you made need to add the proper `securityContext` so mounted volumes are attached with the correct permissions. For instance:
```
apiVersion: v1
kind: Pod
metadata:
  name: splunk
spec:
  securityContext:
    fsGroup: 41812 # this maps to the splunk user in these containers
...
```

Alternatively, you can add an `initContainer` to perform the chown:
```
initContainers:
- name: take-etc-dir-ownership
  image: alpine:3.6
  command:
  - chown
  - -R  
  - 41812:41812
  - /opt/splunk/etc
  volumeMounts:
  - name: splunk-etc
    mountPath: /opt/splunk/etc
```

**Comment by sarit12** [comment]
Thanks !
i used the first option and now im getting this error:

FAILED - RETRYING: Test basic https endpoint (45 retries left).
TASK [splunk_search_head : Check Splunk instance is running] *******************
fatal: [localhost]: FAILED! => {
    "attempts": 60, 
    "changed": false, 
    "content": "", 
    "elapsed": 0, 
    "redirected": false, 
    "status": -1, 
    "url": "http://splunk-master:8089/services/server/info?output_mode=json"
}

MSG:

Status code was -1 and not [200]: Connection failure: [Errno 104] Connection reset by peer
...ignoring

**Comment by nwang92** [comment]
This seemed like an error that was fixed by https://github.com/splunk/splunk-ansible/pull/507, but actually the `Connection reset` may be a legitimate failure. This is generally caused by Splunk failing to start, even though the command `./bin/splunk start` might have appeared to succeed and exit cleanly. 

Going to see if I can repro this in a k8s environment. Are you running the image with any of the feature flags/non-default settings?

**Comment by sarit12** [comment]
Hey
I really appreciate your help!

Im not sure i understand your question:)

**Comment by nwang92** [comment]
Should've been more specific :P Could you show me your kube yaml file for how the container is deployed? And if you have a `default.yml` configmap/secret attached, could you share that as well?

**Comment by sarit12** [comment]
are you referring to this ?
```
`splunk-chart:
  namespace: dev-aviation-02  
  persistence:
    search:
      dataSize: 50Gi
      configSize: 10Gi
    master:
      dataSize: 50Gi
      configSize: 10Gi
    indexer:
      dataSize: 250Gi
      configSize: 10Gi
  app:
    customerName: argus
  configs:
    enabled: true
    ## The image must contain 'indexer','master', and 'search' dirs in /data
    image:
      repository: gcr.io/argussec1/splunk-aviation-configs
      tag: 2.19.0-alpha.ff3cdd3
    env:
      - name: SPLUNK_BEFORE_START_CMD
        value: sudo rm /opt/splunk/var/lib/splunk/kvstore/mongo/mongod.lock

  resources:
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 4

  app:
    customerName: argus
  
  # default configuration loaded by splunk, exposed by nginx
  splunkDefaults:
    defaultYml:
      ansible_post_tasks: null
      ansible_pre_tasks: null
      config:
        baked: default.yml
        defaults_dir: /tmp/defaults
        env:
          headers: null
          var: SPLUNK_DEFAULTS_URL
          verify: true
        host:
          headers: null
          url: null
          verify: true
        max_delay: 60
        max_retries: 3
        max_timeout: 1200
      hide_password: false
      retry_num: 50
      shc_bootstrap_delay: 30
      splunk:
        admin_user: admin
        allow_upgrade: true
        app_paths:
          default: /opt/splunaviationtc/apps
          deployment: /opt/spaviationk/etc/deployment-apps
          httpinput: /opt/splaviation/etc/apps/splunk_httpinput
          idxc: /opt/splunk/eaviationmaster-apps
          shc: /opt/splunk/etaviationhcluster/apps
        enable_service: false
        exec: /opt/splunk/bin/splunk
        group: splunk
        hec_disabled: 0
        hec_enableSSL: 0
        hec_port: 8088
        hec_token: *********-****-****-*****-********
        home: /opt/splunk
        http_enableSSL: 0
        http_enableSSL_cert: null
        http_enableSSL_privKey: null
        http_enableSSL_privKey_password: null
        http_port: 8000
        idxc:
          enable: false
          label: idxc_label
          replication_factor: 3
          replication_port: 9887
          search_factor: 3
          secret: ********
        ignore_license: false
        license_download_dest: /tmp/splunk.lic
        nfr_license: /tmp/nfr_enterprise.lic
        opt: /opt
        password: "" #overriden in the environment variables
        pid: /opt/splunk/var/run/splunk/splunkd.pid
        s2s_enable: true
        s2s_port: 9997
        search_head_cluster_url: null
        secret: null
        shc:
          enable: false
          label: shc_label
          replication_factor: 3
          replication_port: 9887
          secret: ******
        smartstore: null
        svc_port: 8089
        tar_dir: splunk
        user: splunk
        wildcard_license: false
        conf:
          server:
            directory: /opt/splunk/etc/system/local
            content:
              clustering:
                summary_replication : true
      splunk_home_ownership_enforcement: true 
```     
`

**Comment by nwang92** [comment]
That looks correct, I guess this is from some helm chart? I'm not too familiar with the origins of this helm chart, but I don't see anything wrong with the default.yml there. The app paths is incorrect, these should be prefixed with `/opt/splunk` instead of `/opt/splaviation`:
```
        app_paths:
          default: /opt/splunaviationtc/apps
          deployment: /opt/spaviationk/etc/deployment-apps
          httpinput: /opt/splaviation/etc/apps/splunk_httpinput
```
But that shouldn't be the cause of any errors.

So far I haven't had much success reproducing what you're seeing. From your previous error msg:
```
MSG:
Status code was -1 and not [200]: Connection failure: [Errno 104] Connection reset by peer
...ignoring
```
I'm wondering if this is benign - it does appear to ignore these errors, but I'm not sure if that's causing the pod to fail for you. Maybe try the 8.0.5 image tag just published this week to see if that fixes anything for you? The fix for this retry-loop was patched there, wondering if that would solve the problem.
