### ISSUE TITLE
Unsupported config option for services.splunk: 'conf'

### ISSUE THREAD

**Issue by sutcocuk** [splunk/docker-splunk#393]
I get the following error:

Unsupported config option for services.splunk: 'conf'

this is the code:

```
version: "3.6"
networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24      
services:
  splunk:
    conf:
      - key: web
        value:
          directory: /opt/splunk/etc/system/local
          content:
            settings:
              updateCheckerBaseURL: 0 
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
      - 9997:9997
    environment:
      - SPLUNK_PASSWORD=cribldemo
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ADD=index cribl
    networks:
      test:
        ipv4_address: 10.1.0.7     
  cribl-sa:
    image: cribl/cribl:${CRIBL_TAG:-latest}
    ports:
      - 9005:9000
    volumes:
      - ./cribl/sa-local:/opt/cribl/local
    environment:
      - CRIBL_HOME=/opt/cribl
    networks:
      test:
        ipv4_address: 10.1.0.6
```
