### ISSUE TITLE
SPLUNK_HEC_TOKEN is not supported

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#40]
Looking at the https://github.com/splunk/splunk-ansible/search?q=set_as_hec_receiver.yml&unscoped_q=set_as_hec_receiver.yml - seems like you use it only for forwarder and indexer, but not the standalone version.

It is very confusing because you mention this environment variable in advanced configuration https://github.com/splunk/docker-splunk/blob/master/documentation/ADVANCED.md#advanced-configurations

**Comment by outcoldman** [comment]
My `defaults/defaults.yaml`

```
---
retry_num: 50
splunk:
  app_paths:
    default: /opt/splunk/etc/apps
    httpinput: /opt/splunk/etc/apps/splunk_httpinput
    idxc: /opt/splunk/etc/master-apps
    shc: /opt/splunk/etc/shcluster/apps
  exec: /opt/splunk/bin/splunk
  group: splunk
  hec_disabled: 0
  hec_enableSSL: 1
  hec_port: 8088
  hec_token: 9705367d-c294-4c84-b683-327279a23a19
  home: /opt/splunk
  http_port: 8000
  idxc:
    enable: false
    label: idxc_label
    replication_factor: 3
    replication_port: 4001
    search_factor: 3
    secret: lcC+1uges+rIrlEIGDDd0MidOC7MvytL
  opt: /opt
  password: Pc4D4CC4L58S5kQ8tH0MMnpwFjIdP1i/
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  s2s_port: 9997
  shc:
    enable: false
    label: shc_label
    replication_factor: 3
    replication_port: 4001
    secret: mwV+hNdrayEA3dYiyZOfZsFGjV2Acnwx
  svc_port: 8089
  user: splunk
```

And `docker-compose.yml`

```
version: "3.7"

services:

  splunk:
    environment:
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD=password
      - SPLUNK_HEC_TOKEN=57969BB7-DFE9-47A3-8EA3-4A566027487C
    hostname: splunk
    image: splunk/splunk:7.2.0
    ports:
      - "10000:8000"
      - "9088:8088"
      - "10997:9997"
    restart: always
    volumes:
      - ./defaults:/tmp/defaults
```
