### ISSUE TITLE
SPLUNK_ADD does not perform any actions

### ISSUE THREAD

**Issue by ghost** [splunk/docker-splunk#42]
I'm starting Splunk for development purposes using Docker via Ansible like this:
```
---

- name: create volumes for splunk
  docker_volume:
    name: '{{ item }}'
  with_items:
    - opt-splunk-etc
    - opt-splunk-var

- name: create container for splunk
  docker_container:
    name: lbc-splunk
    image: splunk/splunk
    restart_policy: always
    keep_volumes: False
    recreate: True
    networks:
      - name: '{{ lbc_dedicated_network }}'
        ipv4_address: '{{ lbc_dedicated_network_splunk_address }}'
    purge_networks: yes
    published_ports:
      - 8000:8000
    env:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_PASSWORD: devsplunk
      SPLUNK_ADD: tcp 1514 -sourcetype log4j
      USER: root
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
```
but when I try to connect to Splunk - there is no TCP data input source present so I have to add it manually. I had no success calling
```
docker exec /opt/splunk/bin/splunk add tcp 1514 -sourcetype log4j -auth admin:devsplunk
```
too because I receive the following error:
```
stat: /opt/splunk/bin/splunk: No such file or directory
```
Is there any way to overcome the problem? Do I need the Developer License for Splunk to work correctly?
