### ISSUE TITLE
containers are not mounting the var volume

### ISSUE THREAD

**Issue by jmaas** [splunk/docker-splunk#585]
Hi, I'm trying to get `docker-splunk` running and am having issues with the `var` volume which doesn't get mounted inside the container. It is working for the `etc` volume however.

This is my compose file, I've tried this with Docker CE (latest on Ubuntu 22.04) in either a stack/swarm or just with docker-compose:

```
version: "3.6"

networks:
  splunknet:

volumes:
  sh1-etc:
  sh1-var:
  cm1-etc:
  cm1-var:
  idx1-etc:
  idx1-var:
  idx2-etc:
  idx2-var:
  idx3-etc:
  idx3-var:

services:
  sh1:
    networks:
      splunknet:
        aliases:
          - sh1
    image: splunk/splunk:latest
    hostname: sh1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_search_head
    ports:
      - 8000
      - 8089
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
      - sh1-etc:/opt/splunk/etc
      - sh1-var:/opt/splunk/var

  cm1:
    networks:
      splunknet:
        aliases:
          - cm1
    image: splunk/splunk:latest
    command: start
    hostname: cm1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_cluster_master
    ports:
      - 8000
      - 8089
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
      - cm1-etc:/opt/splunk/etc
      - cm1-var:/opt/splunk/var

  idx1:
    networks:
      splunknet:
        aliases:
          - idx1
    image: splunk/splunk:latest
    command: start
    hostname: idx1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
    ports:
      - 8000
      - 8089
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
      - idx1-etc:/opt/splunk/etc
      - idx1-var:/opt/splunk/var

  idx2:
    networks:
      splunknet:
        aliases:
          - idx2
    image: splunk/splunk:latest
    command: start
    hostname: idx2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
    ports:
      - 8000
      - 8089
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
      - idx2-etc:/opt/splunk/etc
      - idx2-var:/opt/splunk/var

  idx3:
    networks:
      splunknet:
        aliases:
          - idx3
    image: splunk/splunk:latest
    command: start
    hostname: idx3
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
    ports:
      - 8000
      - 8089
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
      - idx3-etc:/opt/splunk/etc
      - idx3-var:/opt/splunk/var
```

This is what `df` shows me inside a running container:

```
jmaas@srv1:~/stacks/splunk$ docker container exec 6e96bb385343 df -h
Filesystem                             Size  Used Avail Use% Mounted on
overlay                                500G  5.8G  495G   2% /
tmpfs                                   64M     0   64M   0% /dev
shm                                     64M  176K   64M   1% /dev/shm
/dev/mapper/ubuntu--vg-lv_docker_base  500G  5.8G  495G   2% /etc/hosts
/dev/mapper/ubuntu--vg-lv_root          16G  6.4G  9.7G  40% /tmp/defaults/default.yml
/dev/mapper/ssd--vg-lv_docker_volumes  1.9T   22G  1.8T   2% /opt/splunk/etc
tmpfs                                   32G     0   32G   0% /proc/acpi
tmpfs                                   32G     0   32G   0% /proc/scsi
tmpfs                                   32G     0   32G   0% /sys/firmware
```

Any obvious mistakes? Steps to troubleshoot?
